"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

SECRET_KEY = 'if4+pj+pelq952zq54@uw4m22%(l$qnq_pw*_^b=e^_cac8$99'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third parties
    'rest_framework',
    'social_django',
    # custom
    'users',
    'books'
]
AUTH_USER_MODEL = 'users.User'

SOCIAL_AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bookstore',
        'USER': 'postgres',
        'PASSWORD': os.environ.get('PASS_DB'),
        'HOST': 'localhost',
        'PORT': 5432
    }
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES':
        ['rest_framework.parsers.JSONParser', ],

}

# python-social-auth
SOCIAL_AUTH_POSTGRES_JSONFIELD = True

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
# client_id
SOCIAL_AUTH_GITHUB_KEY = '****b1dc2'
# client_secret
SOCIAL_AUTH_GITHUB_SECRET = '****361968566ae9abffb'

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True

SOCIAL_AUTH_USER_FIELDS = ['user', 'provider', 'uid', 'extra data']
#
# SOCIAL_AUTH_GITHUB_SCOPE = ['email']
# SOCIAL_AUTH_GITHUB_PROFILE_EXTRA_PARAMS = { 'fields': 'id, email' }

# SOCIAL_AUTH_PIPELINE = (
#         'social_core.pipeline.social_auth.social_details',
#         'social_core.pipeline.social_auth.social_uid',
#         'social_core.pipeline.social_auth.social_user',
#         'social_core.pipeline.user.get_username',
#         'social_core.pipeline.social_auth.associate_by_email',
#         'social_core.pipeline.user.create_user',
# 'path.to.save_profile',  # <--- set the path to the function(custom user creation )
#         'social_core.pipeline.social_auth.associate_user',
#         'social_core.pipeline.social_auth.load_extra_data',
#         'social_core.pipeline.user.user_details',
#     )


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
